### ISSUE TITLE
Java 17 support?

### ISSUE THREAD

**Issue by streamtree** [cschabl/activejdbc-gradle-plugin#12]
Is Java 17 supported? Builds fine with 16 but with 17 I'm getting the following error on build:

groovy.lang.MissingPropertyException: Could not get unknown property 'out' for task ':sls:sls-server:instrumentModels' of type de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation.
	at org.gradle.internal.metaobject.AbstractDynamicObject.getMissingProperty(AbstractDynamicObject.java:85)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:62)
	at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.getGroovyObjectProperty(ScriptBytecodeAdapter.java:520)
	at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation.this$dist$get$3(ActiveJDBCInstrumentation.groovy)
	at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation$StdOutCaptor.propertyMissing(ActiveJDBCInstrumentation.groovy)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.5/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.5/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
	at groovy.lang.MetaClassImpl.invokeMissingProperty(MetaClassImpl.java:879)
	at groovy.lang.MetaClassImpl$10.getProperty(MetaClassImpl.java:2120)
	at org.codehaus.groovy.runtime.callsite.GetEffectivePogoPropertySite.getProperty(GetEffectivePogoPropertySite.java:85)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGroovyObjectGetProperty(AbstractCallSite.java:341)
	at de.schablinski.gradle.activejdbc.ActiveJDBCInstrumentation$StdOutCaptor.close(ActiveJDBCInstrumentation.groovy:144)
	at org.gradle.internal.concurrent.CompositeStoppable$2.stop(CompositeStoppable.java:90)
	at org.gradle.internal.concurrent.CompositeStoppable.stop(CompositeStoppable.java:106)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.forwardContent(ExecOutputHandleRunner.java:70)
	at org.gradle.process.internal.streams.ExecOutputHandleRunner.run(ExecOutputHandleRunner.java:53)
	at org.gradle.internal.operations.CurrentBuildOperationPreservingRunnable.run(CurrentBuildOperationPreservingRunnable.java:42)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)

**Comment by cschabl** [comment]
@streamtree ,
which Gradle version did you use?

**Comment by cschabl** [comment]
@streamtree ,
I was able to reproduce the error with Gradle 7.3 (1st version supporting Java 17).
The error must be related to the Java module system, which is activated for the JDK by default in Java 17.

**Comment by streamtree** [comment]
Hi @cschabl…7.5.1

**Comment by cschabl** [comment]
Hi @streamtree ,
I've fixed the issue and published version 2.0.2-beta.1 of the plugin.
Could you verify if the new version fixes your build?

**Comment by streamtree** [comment]
Works like a charm! Thanks for the quick response.
